import { chromium } from 'playwright-core';
const EXE = '/home/user/.cache/ms-playwright/chromium_headless_shell-1243/chrome-headless-shell-linux64/chrome-headless-shell';
const browser = await chromium.launch({ executablePath: EXE, args: ['--enable-unsafe-swiftshader', '--use-angle=swiftshader', '--ignore-gpu-blocklist', '--no-sandbox'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
const errors = [];
page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text().slice(0, 200)); });
page.on('pageerror', (e) => errors.push('PAGEERR ' + e.message.split('\n')[0]));
await page.goto('file:///home/user/viewer_src/dist/index.html', { waitUntil: 'load', timeout: 60000 });
await page.waitForTimeout(6000);
const r = await page.evaluate(async () => {
  const S = window.__viewer;
  const wait = (ms) => new Promise((res) => setTimeout(res, ms));
  const out = { hub: !!(S.hub && S.hubUI && S.exporter), ver: __studio.versions().length, models: S.state.models.length };
  __studio.activate('brandstudio');
  await wait(500);
  out.active = __studio.active();
  out.tiles = ['v6Projects', 'v6Presets', 'v6Backup', 'v6Export', 'v6Workflow', 'v6UndoOpen'].filter((id) => document.getElementById(id)).length;
  out.kits = document.querySelectorAll('.brandstudio .bs-kit').length;
  await S.hub.saveProject('Deliverable Probe');
  out.projects = S.hub.projects().length;
  await S.hub.autosaveNow();
  out.backup = S.hub.hasBackup();
  return out;
});
console.log('PROBE', JSON.stringify(r, null, 1));
console.log('ERRORS', r && r.ver ? errors : errors);
await page.screenshot({ path: 'shots/hub_v6.png' });
await page.waitForTimeout(500);
console.log('shot desktop saved');
await page.close();
const tablet = await browser.newPage({ viewport: { width: 1024, height: 1366 }, hasTouch: true });
await tablet.goto('file:///home/user/viewer_src/dist/index.html', { waitUntil: 'load', timeout: 60000 });
await tablet.waitForTimeout(6000);
await tablet.evaluate(() => __studio.activate('brandstudio'));
await tablet.waitForTimeout(1200);
await tablet.screenshot({ path: 'shots/hub_tablet.png' });
console.log('shot tablet saved');
await browser.close();
