// Product registry — the single source of truth for what the studio can show.
//
// Adding a product (or swapping in a FINAL asset) means:
//   1. a .glb file in public/models/
//   2. one entry in this list
// No component changes. Camera fit, floor, and lighting are all derived
// from whatever model is loaded.
export const PRODUCTS = [
  {
    id: "coffee-bike",
    name: "Coffee Bike",
    label: "Coffee Bike",
    modelPath: "/models/the_kop_refined.glb",
    // World-space azimuth (degrees) the model's FRONT faces. Camera presets
    // are defined relative to this so "Front" always shows the front. The
    // coffee cart/branding faces -X in this asset.
    frontAz: -90,
  },
  {
    // PLACEHOLDER geometry (generated by app/scripts/gen-c172-placeholder.mjs).
    // Replace app/public/models/cessna-172.glb with the final C172 GLB to
    // upgrade — nothing else needs to change.
    id: "cessna-172",
    name: "Cessna 172",
    label: "Cessna 172",
    modelPath: "/models/cessna-172.glb",
    // Nose points +X in this asset.
    frontAz: 90,
  },
];

export function getProduct(id) {
  return PRODUCTS.find((p) => p.id === id) ?? PRODUCTS[0];
}
